# Generated by Django 4.1.7 on 2023-04-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_blog_model_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_model',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
