# Generated by Django 4.1.7 on 2023-04-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blog_model_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
