# Generated by Django 4.1.7 on 2023-04-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_blog_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='image',
            field=models.FileField(null=True, upload_to='II'),
        ),
    ]
