# Generated by Django 4.1.7 on 2023-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_blog_model_author_alter_blog_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
