# Generated by Django 4.1.7 on 2023-04-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_blog_model_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_model',
            name='slug',
        ),
    ]
