# Generated by Django 4.1.7 on 2023-04-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_blog_model_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
