# Generated by Django 4.1.7 on 2023-04-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_blog_model_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_model',
            name='slug',
        ),
    ]
