# Generated by Django 4.1.7 on 2023-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_blog_model_likes_blog_model_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_model',
            name='likes',
        ),
        migrations.AddField(
            model_name='blog_model',
            name='likes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
