# Generated by Django 4.1.7 on 2023-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_blog_model_likes_blog_model_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='likes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
