# Generated by Django 4.2 on 2023-04-21 09:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_blog_model_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_model',
            name='likes',
        ),
        migrations.AddField(
            model_name='blog_model',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='plpl', max_length=512), blank=True, default='sdf', size=None),
        ),
    ]
